// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxS2crzrrjJwUa_munybMVkxs1UMjdDXI',
    appId: '1:261091660605:ios:e0956ac1c72c95750dab54',
    messagingSenderId: '261091660605',
    projectId: 'edu-bus-tracker-5aca1',
    storageBucket: 'edu-bus-tracker-5aca1.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBRDPNsX46flhx5fu5WrlSdt4dahvOGXs',
    appId: '1:261091660605:web:46ddf2cbb385d5600dab54',
    messagingSenderId: '261091660605',
    projectId: 'edu-bus-tracker-5aca1',
    authDomain: 'edu-bus-tracker-5aca1.firebaseapp.com',
    storageBucket: 'edu-bus-tracker-5aca1.firebasestorage.app',
    measurementId: 'G-9324XB47D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQC_R9_o1ptaQEUqAGqQ__pr4tKn53z3M',
    appId: '1:261091660605:android:b85603ed8491cbd60dab54',
    messagingSenderId: '261091660605',
    projectId: 'edu-bus-tracker-5aca1',
    storageBucket: 'edu-bus-tracker-5aca1.firebasestorage.app',
  );
}